sudo: required # it's required to have sudo access (admin)
language: generic

services:
  - docker # saying to travis that we need docker CLI to be installed 

before_install:
  - docker build -t goahead19/React_app_docker -f Dockerfile.dev . # building the image

script:
  - docker run -e CI=true stephengrider/React_app_docker npm run test # running the container