sudo: required # it's required to have sudo access (admin)
language: generic

services:
  - docker # saying to travis that we need docker CLI to be installed 

before_install:
  # building the image
  - docker build -t goahead19/react_app_docker -f Dockerfile.dev . 

script:
  # running the container up
  - docker run -e CI=true goahead19/react_app_docker npm run test -- --coverage
#once the test retrun a status 0 (all tests passed) we can proceed with deploy

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker' #the name of the app created on AWS
  env: 'docker-env' # the environment name of the app created on AWS
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289' #bucket name on S3 
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY