sudo: required # it's required to have sudo access (admin)
language: generic

services:
  - docker # saying to travis that we need docker CLI to be installed 

before_install:
  # building the image
  - docker build -t goahead19/react_app_docker -f Dockerfile.dev . 

script:
  # running the container up
  - docker run -e CI=true stephengrider/react_app_docker npm run test 